### PR TITLE
PY3k compat

### PR DESCRIPTION
**Pull request by meawoppl**
This makes glog work in py3

### CODE REVIEW

**Comment by benley** [comment]
Excellent, thank you!  I ran into this recently as well but forgot to write down a note about fixing it, so this is particularly well timed :-)

**Comment by meawoppl** [comment]
Any chance of getting it pressed to pypi?

**Comment by benley** [comment]
Sure - I'll bump the version number and push an update to pypi tonight.

**Comment by benley** [comment]
Done: https://pypi.python.org/pypi/glog/0.3.1

**Pull request merged**
